import React, { Component } from 'react';
import { Table } from 'antd';

export default class extends Component {
  render() {
    const dataSource = [
      {
        active_withoutnew: "250625",
        day10out: "0",
        day10outrate: "0.0",
        day10return: "0",
        day10returnrate: "0.0",
        day11out: "0",
        day11outrate: "0.0",
        day11return: "0",
        day11returnrate: "0.0",
        day12out: "0",
        day12outrate: "0.0",
        day12return: "0",
        day12returnrate: "0.0",
        day13out: "0",
        day13outrate: "0.0",
        day13return: "0",
        day13returnrate: "0.0",
        day14out: "0",
        day14outrate: "0.0",
        day14return: "0",
        day14returnrate: "0.0",
        day15out: "0",
        day15outrate: "0.0",
        day15return: "0",
        day15returnrate: "0.0",
        day1_pu: "10.06",
        day1out: "7831",
        day1outrate: "100.0",
        day1return: "3860",
        day1returnrate: "49.3",
        day2out: "0",
        day2outrate: "0.0",
        day2return: "0",
        day2returnrate: "0.0",
        day30out: "0",
        day30outrate: "0.0",
        day30return: "0",
        day30returnrate: "0.0",
        day3out: "0",
        day3outrate: "0.0",
        day3return: "0",
        day3returnrate: "0.0",
        day4out: "0",
        day4outrate: "0.0",
        day4return: "0",
        day4returnrate: "0.0",
        day5out: "0",
        day5outrate: "0.0",
        day5return: "0",
        day5returnrate: "0.0",
        day6out: "0",
        day6outrate: "0.0",
        day6return: "0",
        day6returnrate: "0.0",
        day7out: "0",
        day7outrate: "0.0",
        day7return: "0",
        day7returnrate: "0.0",
        day8out: "0",
        day8outrate: "0.0",
        day8return: "0",
        day8returnrate: "0.0",
        day9out: "0",
        day9outrate: "0.0",
        day9return: "0",
        day9returnrate: "0.0",
        dayinstallstart: 14831,
        dt: "20190609",
        idfa_install: 11992,
        idfa_online: 258456,
        installuser: "7831",
        installuser_uncheat: "7808",
        new_baishi_cnt: "1728",
        new_bemaster_apprcnt: "195",
        new_shoutu_cnt: "146",
        os: "android",
        qid: "vivo",
        rate: 0,
        softname: "东方头条",
        todayapprentice: "2427",
        todaymaster: "475",
        totalapprentice: "7587",
        totalmaster: "1614"
      },
      {
        active_withoutnew: "272168",
        day10out: "0",
        day10outrate: "0.0",
        day10return: "0",
        day10returnrate: "0.0",
        day11out: "0",
        day11outrate: "0.0",
        day11return: "0",
        day11returnrate: "0.0",
        day12out: "0",
        day12outrate: "0.0",
        day12return: "0",
        day12returnrate: "0.0",
        day13out: "0",
        day13outrate: "0.0",
        day13return: "0",
        day13returnrate: "0.0",
        day14out: "0",
        day14outrate: "0.0",
        day14return: "0",
        day14returnrate: "0.0",
        day15out: "0",
        day15outrate: "0.0",
        day15return: "0",
        day15returnrate: "0.0",
        day1_pu: "12.63",
        day1out: "7710",
        day1outrate: "100.0",
        day1return: "4157",
        day1returnrate: "53.9",
        day2out: "0",
        day2outrate: "0.0",
        day2return: "0",
        day2returnrate: "0.0",
        day30out: "0",
        day30outrate: "0.0",
        day30return: "0",
        day30returnrate: "0.0",
        day3out: "0",
        day3outrate: "0.0",
        day3return: "0",
        day3returnrate: "0.0",
        day4out: "0",
        day4outrate: "0.0",
        day4return: "0",
        day4returnrate: "0.0",
        day5out: "0",
        day5outrate: "0.0",
        day5return: "0",
        day5returnrate: "0.0",
        day6out: "0",
        day6outrate: "0.0",
        day6return: "0",
        day6returnrate: "0.0",
        day7out: "0",
        day7outrate: "0.0",
        day7return: "0",
        day7returnrate: "0.0",
        day8out: "0",
        day8outrate: "0.0",
        day8return: "0",
        day8returnrate: "0.0",
        day9out: "0",
        day9outrate: "0.0",
        day9return: "0",
        day9returnrate: "0.0",
        dayinstallstart: 16593,
        dt: "20190609",
        idfa_install: 12962,
        idfa_online: 279878,
        installuser: "7710",
        installuser_uncheat: "7699",
        new_baishi_cnt: "1617",
        new_bemaster_apprcnt: "218",
        new_shoutu_cnt: "173",
        os: "android",
        qid: "oppo",
        rate: 0,
        softname: "东方头条",
        todayapprentice: "2165",
        todaymaster: "545",
        totalapprentice: "7085",
        totalmaster: "1830"
      },
      {
        active_withoutnew: "478722",
        day10out: "0",
        day10outrate: "0.0",
        day10return: "0",
        day10returnrate: "0.0",
        day11out: "0",
        day11outrate: "0.0",
        day11return: "0",
        day11returnrate: "0.0",
        day12out: "0",
        day12outrate: "0.0",
        day12return: "0",
        day12returnrate: "0.0",
        day13out: "0",
        day13outrate: "0.0",
        day13return: "0",
        day13returnrate: "0.0",
        day14out: "0",
        day14outrate: "0.0",
        day14return: "0",
        day14returnrate: "0.0",
        day15out: "0",
        day15outrate: "0.0",
        day15return: "0",
        day15returnrate: "0.0",
        day1_pu: "14.62",
        day1out: "6746",
        day1outrate: "100.0",
        day1return: "4831",
        day1returnrate: "71.6",
        day2out: "0",
        day2outrate: "0.0",
        day2return: "0",
        day2returnrate: "0.0",
        day30out: "0",
        day30outrate: "0.0",
        day30return: "0",
        day30returnrate: "0.0",
        day3out: "0",
        day3outrate: "0.0",
        day3return: "0",
        day3returnrate: "0.0",
        day4out: "0",
        day4outrate: "0.0",
        day4return: "0",
        day4returnrate: "0.0",
        day5out: "0",
        day5outrate: "0.0",
        day5return: "0",
        day5returnrate: "0.0",
        day6out: "0",
        day6outrate: "0.0",
        day6return: "0",
        day6returnrate: "0.0",
        day7out: "0",
        day7outrate: "0.0",
        day7return: "0",
        day7returnrate: "0.0",
        day8out: "0",
        day8outrate: "0.0",
        day8return: "0",
        day8returnrate: "0.0",
        day9out: "0",
        day9outrate: "0.0",
        day9return: "0",
        day9returnrate: "0.0",
        dayinstallstart: 6614,
        dt: "20190609",
        idfa_install: 8346,
        idfa_online: 485468,
        installuser: "6746",
        installuser_uncheat: "6743",
        new_baishi_cnt: "5459",
        new_bemaster_apprcnt: "316",
        new_shoutu_cnt: "196",
        os: "android",
        qid: "gf1",
        rate: 0,
        softname: "东方头条",
        todayapprentice: "3343",
        todaymaster: "856",
        totalapprentice: "10336",
        totalmaster: "2792"
      },
      {
        active_withoutnew: "331353",
        day10out: "0",
        day10outrate: "0.0",
        day10return: "0",
        day10returnrate: "0.0",
        day11out: "0",
        day11outrate: "0.0",
        day11return: "0",
        day11returnrate: "0.0",
        day12out: "0",
        day12outrate: "0.0",
        day12return: "0",
        day12returnrate: "0.0",
        day13out: "0",
        day13outrate: "0.0",
        day13return: "0",
        day13returnrate: "0.0",
        day14out: "0",
        day14outrate: "0.0",
        day14return: "0",
        day14returnrate: "0.0",
        day15out: "0",
        day15outrate: "0.0",
        day15return: "0",
        day15returnrate: "0.0",
        day1_pu: "12.56",
        day1out: "6522",
        day1outrate: "100.0",
        day1return: "3939",
        day1returnrate: "60.4",
        day2out: "0",
        day2outrate: "0.0",
        day2return: "0",
        day2returnrate: "0.0",
        day30out: "0",
        day30outrate: "0.0",
        day30return: "0",
        day30returnrate: "0.0",
        day3out: "0",
        day3outrate: "0.0",
        day3return: "0",
        day3returnrate: "0.0",
        day4out: "0",
        day4outrate: "0.0",
        day4return: "0",
        day4returnrate: "0.0",
        day5out: "0",
        day5outrate: "0.0",
        day5return: "0",
        day5returnrate: "0.0",
        day6out: "0",
        day6outrate: "0.0",
        day6return: "0",
        day6returnrate: "0.0",
        day7out: "0",
        day7outrate: "0.0",
        day7return: "0",
        day7returnrate: "0.0",
        day8out: "0",
        day8outrate: "0.0",
        day8return: "0",
        day8returnrate: "0.0",
        day9out: "0",
        day9outrate: "0.0",
        day9return: "0",
        day9returnrate: "0.0",
        dayinstallstart: 15498,
        dt: "20190609",
        idfa_install: 10802,
        idfa_online: 337875,
        installuser: "6522",
        installuser_uncheat: "6484",
        new_baishi_cnt: "1216",
        new_bemaster_apprcnt: "139",
        new_shoutu_cnt: "107",
        os: "android",
        qid: "huawei",
        rate: 0,
        softname: "东方头条",
        todayapprentice: "2195",
        todaymaster: "433",
        totalapprentice: "7146",
        totalmaster: "1685"
      },
    ];
    
    const columns = [
      {
        title: '日期',
        dataIndex: 'dt',
      },
      {
        title: '渠道',
        dataIndex: 'qid',
        render: text => <a>{ text }</a>
      },
      {
        title: '操作系统',
        dataIndex: 'os',
      },
      {
        title: '软件名称',
        dataIndex: 'softname',
      },
      {
        title: '全库去重安装数',
        dataIndex: 'installuser',
        sorter: (a, b) => a.installuser - b.installuser,
      },
      {
        title: 'IDFA安装量',
        dataIndex: 'idfa_install',
        sorter: (a, b) => a.idfa_install - b.idfa_install,
      },
      {
        title: 'IDFA活跃数',
        dataIndex: 'idfa_online',
        sorter: (a, b) => a.idfa_online - b.idfa_online,
      },
      {
        title: '版本分布',
        dataIndex: 'banben',
      },
      {
        title: '用户分布',
        dataIndex: 'yonghu',
      },
      {
        title: '第1日',
        children: [
          {
            title: '外活率',
            dataIndex: 'day1outrate',
            sorter: (a, b) => a.day1outrate - b.day1outrate,
            render: text => <span className="text-danger">{ text +'%' }</span>
          },
          {
            title: '内活率',
            dataIndex: 'day1returnrate',
            sorter: (a, b) => a.day1returnrate - b.day1returnrate,
            render: text => <span className="text-success">{ text + '%' }</span>
          },
          {
            title: '外活数',
            dataIndex: 'day1out',
          },
          {
            title: '内活数',
            dataIndex: 'day1return',
          },
        ]
      },
      {
        title: '第2日',
        children: [
          {
            title: '外活率',
            dataIndex: 'day2outrate',
          },
          {
            title: '内活率',
            dataIndex: 'day2returnrate',
          },
          {
            title: '外活数',
            dataIndex: 'day2out',
          },
          {
            title: '内活数',
            dataIndex: 'day2return',
          },
        ]
      },
      {
        title: '第3日',
        children: [
          {
            title: '外活率',
            dataIndex: 'day3outrate',
          },
          {
            title: '内活率',
            dataIndex: 'day3returnrate',
          },
          {
            title: '外活数',
            dataIndex: 'day3out',
          },
          {
            title: '内活数',
            dataIndex: 'day3return',
          },
        ]
      },
      {
        title: '第4日',
        children: [
          {
            title: '外活率',
            dataIndex: 'day4outrate',
          },
          {
            title: '内活率',
            dataIndex: 'day4returnrate',
          },
          {
            title: '外活数',
            dataIndex: 'day4out',
          },
          {
            title: '内活数',
            dataIndex: 'day4return',
          },
        ]
      },
      {
        title: '第5日',
        children: [
          {
            title: '外活率',
            dataIndex: 'day5outrate',
          },
          {
            title: '内活率',
            dataIndex: 'day5returnrate',
          },
          {
            title: '外活数',
            dataIndex: 'day5out',
          },
          {
            title: '内活数',
            dataIndex: 'day5return',
          },
        ]
      },
      {
        title: '第6日',
        children: [
          {
            title: '外活率',
            dataIndex: 'day6outrate',
          },
          {
            title: '内活率',
            dataIndex: 'day6returnrate',
          },
          {
            title: '外活数',
            dataIndex: 'day6out',
          },
          {
            title: '内活数',
            dataIndex: 'day6return',
          },
        ]
      },
      {
        title: '第7日',
        children: [
          {
            title: '外活率',
            dataIndex: 'day7outrate',
          },
          {
            title: '内活率',
            dataIndex: 'day7returnrate',
          },
          {
            title: '外活数',
            dataIndex: 'day7out',
          },
          {
            title: '内活数',
            dataIndex: 'day7return',
          },
        ]
      },
      {
        title: '第15日',
        children: [
          {
            title: '外活率',
            dataIndex: 'day15outrate',
          },
          {
            title: '内活率',
            dataIndex: 'day15returnrate',
          },
          {
            title: '外活数',
            dataIndex: 'day15out',
          },
          {
            title: '内活数',
            dataIndex: 'day15return',
          },
        ]
      },
      {
        title: '第30日',
        children: [
          {
            title: '外活率',
            dataIndex: 'day30outrate',
          },
          {
            title: '内活率',
            dataIndex: 'day30returnrate',
          },
          {
            title: '外活数',
            dataIndex: 'day30out',
          },
          {
            title: '内活数',
            dataIndex: 'day30return',
          },
        ]
      },
    ];

    return (
      <Table
        size="small"
        bordered={true}
        dataSource={dataSource}
        columns={columns}
        rowKey={(record, i) => i}
        scroll={{ x: '100%' }}
        pagination={false} />
    )
  }
}