"""empty message

Revision ID: 0533b1bd4601
Revises: b60606d5e942
Create Date: 2019-05-06 11:35:38.256000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0533b1bd4601'
down_revision = 'b60606d5e942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('description', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'])
    op.drop_column('articles', 'desc')
    op.create_foreign_key(None, 'comments', 'articles', ['article_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'articles', ['user_id'], ['id'])
    op.create_foreign_key(None, 'plates', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plates', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.add_column('articles', sa.Column('desc', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'description')
    # ### end Alembic commands ###
