"""empty message

Revision ID: 344f1697ab7c
Revises: 0533b1bd4601
Create Date: 2019-05-06 17:38:07.058000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '344f1697ab7c'
down_revision = '0533b1bd4601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'articles', 'categories', ['category_id'], ['id'])
    op.drop_column('articles', 'author_id')
    op.create_foreign_key(None, 'comments', 'articles', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'articles', ['article_id'], ['id'])
    op.create_foreign_key(None, 'plates', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plates', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.add_column('articles', sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'user_id')
    op.drop_column('articles', 'category_id')
    # ### end Alembic commands ###
