"""empty message

Revision ID: 7d8df5057392
Revises: aceb9a52fa8a
Create Date: 2019-07-31 20:20:42.043000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d8df5057392'
down_revision = 'aceb9a52fa8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article_tag', 'articles', ['article_id'], ['id'])
    op.create_foreign_key(None, 'article_tag', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'articles', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'comments', ['refer_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'articles', ['article_id'], ['id'])
    op.create_foreign_key(None, 'userinfos', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'token',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'token',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)
    op.drop_constraint(None, 'userinfos', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'article_tag', type_='foreignkey')
    op.drop_constraint(None, 'article_tag', type_='foreignkey')
    # ### end Alembic commands ###
