"""empty message

Revision ID: b60606d5e942
Revises: e316a280af3a
Create Date: 2019-04-26 14:11:37.139000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b60606d5e942'
down_revision = 'e316a280af3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'])
    op.add_column('categories', sa.Column('order_num', sa.Integer(), nullable=True))
    op.drop_column('categories', 'ordNum')
    op.create_foreign_key(None, 'comments', 'articles', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'articles', ['article_id'], ['id'])
    op.add_column('plates', sa.Column('order_num', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plates', 'categories', ['category_id'], ['id'])
    op.drop_column('plates', 'ordNum')
    op.add_column('tags', sa.Column('order_num', sa.Integer(), nullable=True))
    op.drop_column('tags', 'ordNum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('ordNum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('tags', 'order_num')
    op.add_column('plates', sa.Column('ordNum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plates', type_='foreignkey')
    op.drop_column('plates', 'order_num')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.add_column('categories', sa.Column('ordNum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('categories', 'order_num')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    # ### end Alembic commands ###
