"""empty message

Revision ID: bfbab5d0edbe
Revises: b6d582f32223
Create Date: 2019-05-07 14:30:32.126000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfbab5d0edbe'
down_revision = 'b6d582f32223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article_tag', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'article_tag', 'articles', ['article_id'], ['id'])
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'articles', 'categories', ['category_id'], ['id'])
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.add_column('comments', sa.Column('refer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['refer_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'articles', ['article_id'], ['id'])
    op.alter_column('tags', 'name',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_foreign_key(None, 'userinfos', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userinfos', type_='foreignkey')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.alter_column('tags', 'name',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'refer_id')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'article_tag', type_='foreignkey')
    op.drop_constraint(None, 'article_tag', type_='foreignkey')
    # ### end Alembic commands ###
