"""empty message

Revision ID: e316a280af3a
Revises: 0b07355f92c0
Create Date: 2019-04-26 14:10:53.262000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e316a280af3a'
down_revision = '0b07355f92c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'articles', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'articles', ['article_id'], ['id'])
    op.create_foreign_key(None, 'plates', 'categories', ['category_id'], ['id'])
    op.add_column('roles', sa.Column('role_id', sa.Integer(), nullable=False))
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('roles', 'role_id')
    op.drop_constraint(None, 'plates', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    # ### end Alembic commands ###
